name: First Project Deployment

on:
  push:
    branches: [ master ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install NodeJS
      uses: actions/setup.node@v2-beta
      with:
        noder-version: 12
        
    - name: install surge
        run: npm install -g surge
      
    - name: Run Surge
      run:  surge ./ helloword.surge.sh --token ${{secrets.surge_token}}
